### ISSUE TITLE
Python demo should use Cloud Storage not the Files API

### ISSUE THREAD

**Issue by johnalowry** [GoogleCloudPlatform/appengine-mapreduce#26]
python/demo/main.py currently uses:

        "mapreduce.input_readers.BlobstoreZipInputReader",
        "mapreduce.output_writers.BlobstoreOutputWriter",

The demo should use Cloud Storage, since the Files API is deprecated.

A GCSZipFileReader will likely need to be written.

**Comment by w4-steve** [comment]
+1

**Comment by kolibeer** [comment]
I don't think BlobstoreZipInputReader uses files api.

**Comment by lucena** [comment]
The current demo now works properly and without the Files API.
BlobstoreZipInputReader does not use the Files API and blobkeys can be generated from files stored in Google Cloud Storage so that they can be accessed by Blobstore APIs that use keys.
However it would be nice for someone to implement a GCSZipInputReader so that the demo could be based completely on GCS and not rely on Blobstore.

**Comment by w4-steve** [comment]
```python
    blob_key = params[cls.BLOB_KEY_PARAM]
    blob_info = blobstore.BlobInfo.get(blobstore.BlobKey(blob_key))
    if not blob_info:
      raise BadReaderParamsError("Could not find blobinfo for key %s" %
                                 blob_key)
```

Any Blobstore reader needs BlobInfo but generated blob keys do not support BlobInfo

> (However, BlobInfo objects are currently not available for GCS objects.)
